# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Define the VM configuration
  config.vm.define "container_intro" do |node|
    # Set the box (OS image) to use
    node.vm.box = "bento/ubuntu-20.04"
    
    # Set private IP
    node.vm.network "private_network", ip: "192.168.56.6"
    
    # Set hostname
    node.vm.hostname = "container-intro"
    
    # Provider-specific configuration
    node.vm.provider "virtualbox" do |vb|
      # Customize VM settings if needed
      # Example:
      vb.memory = "1024"
    end
    
    # Provisioning
    node.vm.provision "shell", path: "provision.sh"
  end
end
