# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Configure the box name
  config.vm.box = "ubuntu/jammy64" 
  
  # Configure private network
  config.vm.network "private_network", ip: "192.168.56.4"
  
  # Configure the box name
  config.vm.hostname = "wordpress"   
  
  # Configure shell provisioner
  config.vm.provision "shell", path: "provision.sh"
  
  # Customize the VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024" # Customize memory size if needed
    vb.cpus = 2 # Customize CPU cores if needed
  end
end
