Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
      
    ### DB vm  ####
    config.vm.define "pyscriptvm" do |cv|
      cv.vm.box = "ubuntu/jammy64"
      cv.vm.hostname = "pyscriptvm"
      cv.vm.network "private_network", ip: "192.168.56.20"
      cv.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
    end
    ### DB vm  ####
    config.vm.define "pyweb01vm" do |web01|
      web01.vm.box = "eurolinux-vagrant/centos-stream-9"
      web01.vm.hostname = "pyweb01vm"
      web01.vm.network "private_network", ip: "192.168.56.21"
      web01.vm.provider "virtualbox" do |vb|
        vb.memory = "800"
    end
    end
    ### Nginx VM ###
    config.vm.define "pyweb02vm" do |web02|
      web02.vm.box = "ubuntu/jammy64"
      web02.vm.hostname = "pyweb02vm"
      web02.vm.network "private_network", ip: "192.168.56.22"
      web02.vm.provider "virtualbox" do |vb|
        vb.memory = "800"
      end
    end
    
  end
  